services:
  - type: web
    name: forensiq-dashboard
    env: node
    rootDir: .
    buildCommand: "cd frontend && npm install && npm run build && cd ../backend && npm install"
    startCommand: "cd backend && NODE_ENV=production node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
